# Generated by Django 5.0.1 on 2025-12-08 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('time_control', models.CharField(max_length=10)),
                ('initial_time', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('white_time_left', models.IntegerField()),
                ('black_time_left', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('1/2-1/2', 'Draw'), ('*', 'Ongoing')], default='*', max_length=10)),
                ('termination', models.CharField(blank=True, max_length=50)),
                ('current_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('initial_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('pgn', models.TextField(blank=True)),
                ('move_count', models.IntegerField(default=0)),
                ('current_turn', models.CharField(default='white', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('white_rating_before', models.IntegerField(default=1200)),
                ('black_rating_before', models.IntegerField(default=1200)),
                ('white_rating_after', models.IntegerField(blank=True, null=True)),
                ('black_rating_after', models.IntegerField(blank=True, null=True)),
                ('spectator_count', models.IntegerField(default=0)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_control', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matchmaking_queue',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('color', models.CharField(max_length=5)),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('piece', models.CharField(max_length=10)),
                ('captured_piece', models.CharField(blank=True, max_length=10)),
                ('promotion', models.CharField(blank=True, max_length=10)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('is_castling', models.BooleanField(default=False)),
                ('is_en_passant', models.BooleanField(default=False)),
                ('algebraic_notation', models.CharField(max_length=10)),
                ('fen_after', models.TextField()),
                ('time_spent', models.IntegerField()),
                ('time_left', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
            options={
                'db_table': 'moves',
                'ordering': ['move_number', 'id'],
                'unique_together': {('game', 'move_number', 'color')},
            },
        ),
    ]
